### ISSUE TITLE
Base jinja template for report.

### ISSUE THREAD

**Issue by cassimons** [populationgenomics/automated-interpretation-pipeline#161]
Hey @daniaki, just jotting down my request from the meeting yesterday.

Based on our previous discussions, I think we all reached a consensus that moving to jinja based templates with some minimal js affordances was likely to be the most simple and maintainable way to build these types of simple standalone HTML reports. Could we please get your help to set up a suitable jinja base template we can build from for the AIP report (and other similar reports in the future)?

The requirements are simple, just a base template with suitable default CSS to look presentable and set up to use [datatables](https://datatables.net/). I do not think it is worth your time to re-implementing the full existing report, but enough of an example demonstrating how we could use template inheritance to modularise report components would be helpful.

**Comment by daniaki** [comment]
Thanks for the description @cassimons!

I'm going to modify @MattWellie original implementation so that it renders into a base jinja template with CSS styling and Datatables - it won't be the prettiest solution but it will be start. Is this ok? The current solution is using pandas to render html tables, so as a next step it might be worth looking at how this can be re-implement these in jinja.

**Comment by MattWellie** [comment]
JINJA IS LIVE
